baseURL = "https://sync-e.nwtime.org/"
title = "SyncE Project"
enableRobotsTXT = true

[params.plugins]

# JS Plugins
  [[params.plugins.js]]
  link = "plugins/bootstrap-5.1.3/js/bootstrap.bundle.min.js"

contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsUseClassic = false
pygmentsStyle = "tango"

[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true

[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[languages]
[languages.en]
contentDir = "content/en"
title = "SyncE Project"
languageName ="English"
weight = 1

##### needed for raw html in md files #####
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
      style = "tango"

# Everything below this are Site Params

[params]
copyright = "Network Time Foundation"
logo2 = "images/logo.png"
github_repo = "https://github.com/nwtime"
description = "SyncE Project"
images = ["/images/featured.webp"]

# Define Content Security Policy
[params.csp]
  defaultsrc = ["'self'"]
  connectsrc = ["'self'", "https://www.clarity.ms", "https://j.clarity.ms", "https://www.google-analytics.com"]
  childsrc = ["'self'"]
  fontsrc = ["'self'", "https://fonts.gstatic.com"]
  formaction = ["'self'"]
  framesrc = ["'self'"]
  imgsrc = ["'self'", "'unsafe-inline'", "'unsafe-eval'", "https://www.google-analytics.com",  "https://www.googletagmanager.com", "https://www.google.com", "https://clients1.google.com", "https://www.googleapis.com", "https://cse.google.com", "https://encrypted-tbn0.gstatic.com", "https://encrypted-tbn3.gstatic.com", "https://c.clarity.ms", "https://c.bing.com"]
  objectsrc = ["'none'"]
  stylesrc = ["'self'", "'unsafe-inline'", "https://fonts.googleapis.com", "https://cse.google.com", "https://www.google.com"]
  scriptsrc = ["'self'", "'unsafe-inline'", "'unsafe-eval'", "https://www.google-analytics.com", "https://www.googletagmanager.com", "https://cse.google.com", "https://www.google.com", "https://www.clarity.ms"]

[params.links]
[[params.links.user]]
	name = "Mailing lists"
	url = "https://lists.nwtime.org"
	icon = "/images/icons/envelope.svg"
        desc = "SyncE Mailing Lists"